<main class="container py-5">  
    <article class="card col-12 p-5">  
        <header>  
            <h2 class="card-title mb-3">  
                <?php echo $data["product"]->getName(); ?>
            </h2>  
            <h3 class="card-subtitle mb-4">  
                <?php echo implode(', ', $data["product"]->getCategories()); ?>
            </h3>  
        </header>  
        <p class="card-text">  
            <?php echo $data["product"]->getDescription(); ?>
        </p>  
        <footer>  
            <p class="btn btn-light">  
                Prix du film <?php echo $data["product"]->getPrice(); ?> €
            </p>  
        </footer>  
    </article>  
</main>
